### ISSUE TITLE
how to uuse package?

### ISSUE THREAD

**Issue by vtolstov** [bbuck/go-lexer#2]
Hi! I'm need to parse something like:
```
# begin crush map

# devices
device 0 osd.0
device 1 osd.1
device 2 osd.2
device 3 osd.3

# types
type 0 osd
type 1 host
type 2 rack
type 3 row
type 4 room
type 5 datacenter
type 6 pool

# buckets
host ceph-01 {
    id -2       # do not change unnecessarily
    # weight 3.000
    alg straw
    hash 0  # rjenkins1
    item osd.0 weight 1.000
    item osd.1 weight 1.000
}
```

Can you provide some info how to use you package ?

**Comment by bbuck** [comment]
This is just a lexer, I'm not sure if you're using the term "parse" literally or not.

You would build your state functions to match against the various kinds of data, it looks like at the top level you'd want to know if you have a `device` or a `type` (could switch off first character, returning appropriate state function). Then the `host` state gets a bit more complex since it essentially seems to have it's own state.

A state function is a lexing state, so it should examine the current state and decide where to go from there.

For example, the top-level state function might do something like (psuedocode):

```
switch currentChar {
  when 'd' -> return deviceState
  when 't' -> return typeState
  when 'h' -> return hostState
  when '#' -> return commentState
  else -> throw LexError
}
```

This will just emit a stream of tokens though, you'll need a parser to handle them. For example the output might be things like: `[DEVICE, (NUMBER, 0), (STRING, '0.osd'), ...]`

**Comment by vtolstov** [comment]
Thanks,i'm use you lexer (slightly modify it) and write https://github.com/sdstack/go-crush/tree/master/crushmap

**Comment by bbuck** [comment]
Awesome, glad you were able to fit into your project!
